
name: Build webgoat app

on: push
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn --batch-mode clean package -Dmaven.test.skip=true 

    - name: Evaluate with Sonatype CLI
      id: evaluate
      uses: sonatype/actions/evaluate@v1
      with:
        iq-server-url: https://84e2-2a00-23c7-6428-8001-ecfc-4f0f-1bd3-f0aa.ngrok-free.app
        username: admin
        password: admin123
        application-id: webgoat3_gha
        scan-targets: target/*.war

     
   
