
name: Build webgoat app

on: push
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v43.0.1
      with:
        configurationFile: rconfig/renovate_config.json
        token: ${{ secrets.RENOVATE_TOKEN }}
     
   
